Sign In
jrodriguezRS/target-app pull request #1
Opened 2021-03-12 18:13 UTC by juanRodriguez17

#### Description
* API url changed
* Sign in to the app with the respective backend flow
* Sign in screen according to designs

---

#### Preview
* ![image](https://user-images.githubusercontent.com/79857303/110980760-f799d200-8344-11eb-92c3-db6a0d330a05.png)

2021-03-12 18:47 UTC, ximenaperez requested changes
nice work! it seems the image is cut off on the screenshot though

2021-03-12 18:47 UTC, ximenaperez commented on app/src/main/res/drawable/edittext_backgorund_error.xml
> +</shape>
add an extra line at the end of the file

2021-03-12 18:50 UTC, amaury901130 approved these changes
Nice, please check this design, I think this is wrong.
<img width="259" alt="Screen Shot 2021-03-12 at 15 47 24" src="https://user-images.githubusercontent.com/17047904/110984926-8a893b00-834a-11eb-8426-bb52287de679.png">

2021-03-12 18:52 UTC, amaury901130 commented on app/src/main/java/com/rootstrap/android/ui/activity/main/SignInActivity.kt
> +        binding.passwordEditText.setOnFocusChangeListener { _, _ -> changeBackground(binding.passwordEditText) }
please use `binding.apply{.....}`

2021-03-15 12:43 UTC, juanRodriguez17 commented on app/src/main/java/com/rootstrap/android/ui/activity/main/SignInActivity.kt
> +        binding.passwordEditText.setOnFocusChangeListener { _, _ -> changeBackground(binding.passwordEditText) }
It has more sense, changed! Thanks

2021-03-15 13:00 UTC, juanRodriguez17 commented on app/src/main/res/drawable/edittext_backgorund_error.xml
> +</shape>
Done! Also the image `scaleType` property was changed in order to fix the cut off problem

2021-03-15 14:41 UTC, ximenaperez approved these changes

2021-03-15 14:41 UTC, ximenaperez commented on app/src/main/res/drawable/edittext_background.xml
> +</shape>
same here

2021-03-15 15:20 UTC, merged